inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  UseCache: true
  CacheRootDirectory: tmp/rubocop
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'tmp/**/*'
    - vendor/**/*
    - Rakefile
    - config/boot.rb

Rails:
  Enabled: true

Style/Alias:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AsciiComments:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/AbcSize:
  Max: 19

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/WordArray:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
