language: ruby
cache: bundler
sudo: false

script: "bundle exec rake"

rvm:
  - 2.4.1

env:
  - DB=sqlite

before_script:
  - bundle exec rake app:db:setup

bundler_args: "--binstubs --without tools"

# IRC notification
notifications:
  irc: "irc.freenode.org#cyt"
