language: ruby
cache: bundler
sudo: false

script: "bundle exec rake"

rvm:
  - 2.3
  - 2.4
  - 2.6

env:
  - DB=sqlite

before_script:
  - gem update --system
  - gem install bundler:1.17.3
  - bundle install
  - bundle exec rake app:db:setup

bundler_args: "--binstubs --without tools"

# IRC notification
notifications:
  irc: "irc.freenode.org#cyt"
